### ISSUE TITLE
PHP error when installing via console

### ISSUE THREAD

**Issue by brandonkelly** [verbb/comments#157]
### Description

When installing Comments via the console, the following error occurs:

> yii\base\UnknownMethodException: Calling unknown method: craft\console\Request::getBodyParam() in /home/vagrant/dev/support/craft3.support.test/vendor/yiisoft/yii2/base/Component.php:300

Stack trace:

```
#0 /home/vagrant/dev/support/craft3.support.test/vendor/craftcms/cms/src/services/Fields.php(1130): yii\base\Component->__call()
#1 /home/vagrant/dev/support/craft3.support.test/vendor/verbb/comments/src/services/CommentsService.php(645): craft\services\Fields->assembleLayoutFromPost()
#2 /home/vagrant/dev/support/craft3.support.test/vendor/verbb/comments/src/Comments.php(241): verbb\comments\services\CommentsService->saveFieldLayout()
#3 [internal function]: verbb\comments\Comments->verbb\comments\{closure}()
#4 /home/vagrant/dev/support/craft3.support.test/vendor/yiisoft/yii2/base/Event.php(312): call_user_func()
#5 /home/vagrant/dev/support/craft3.support.test/vendor/yiisoft/yii2/base/Component.php(636): yii\base\Event::trigger()
#6 /home/vagrant/dev/support/craft3.support.test/vendor/craftcms/cms/src/services/Plugins.php(712): yii\base\Component->trigger()
#7 /home/vagrant/dev/support/craft3.support.test/vendor/verbb/comments/src/Comments.php(111): craft\services\Plugins->savePluginSettings()
#8 /home/vagrant/dev/support/craft3.support.test/vendor/craftcms/cms/src/base/Plugin.php(153): verbb\comments\Comments->afterInstall()
#9 /home/vagrant/dev/support/craft3.support.test/vendor/craftcms/cms/src/services/Plugins.php(517): craft\base\Plugin->install()
```

`craft\services\Fields::assembleLayoutFromPost()` should only be called on web requests.

### Steps to reproduce

1. Attempt to install Comments from the Terminal via `./craft install/plugin comments`.

### Additional info

- Plugin version: 1.3.3
- Craft version: 3.4.4.1

**Comment by engram-design** [comment]
Fixed in [1.3.4](https://github.com/verbb/comments/releases/tag/1.3.4)
