### ISSUE TITLE
Cannot open comments dashboard after upgrading to Craft 5

### ISSUE THREAD

**Issue by robinbisping** [verbb/comments#300]
### Describe the bug

After upgrading to Craft 5, the comments dashboard `/admin/comments` is unable to load comments.

The request to `/index.php?p=admin%2Factions%2Felement-indexes%2Fget-elements&v=1716747786872` causes the following error:

```
2024-05-26 20:18:45 [web.ERROR] [TypeError] TypeError: verbb\comments\elements\Comment::__toString(): Return value must be of type string, null returned in /var/www/html/vendor/verbb/comments/src/elements/Comment.php:303
Stack trace:
#0 /var/www/html/vendor/craftcms/cms/src/helpers/Cp.php(681): verbb\comments\elements\Comment->__toString()
#1 /var/www/html/vendor/craftcms/cms/src/helpers/Cp.php(464): craft\helpers\Cp::baseElementAttributes(Object(verbb\comments\elements\Comment), Array)
#2 /var/www/html/storage/runtime/compiled_templates/a1/a10e9bdf5e9b5f93ff24be8b4a01637a.php(159): craft\helpers\Cp::elementChipHtml(Object(verbb\comments\elements\Comment), Array)
#3 /var/www/html/vendor/twig/twig/src/Template.php(394): __TwigTemplate_87f7349854444bd09549272799121dcb->doDisplay(Array, Array)
#4 /var/www/html/vendor/twig/twig/src/Template.php(367): Twig\Template->displayWithErrorHandling(Array, Array)
#5 /var/www/html/storage/runtime/compiled_templates/77/77f8c87cd1b28907a1d95e182c8e1cb9.php(150): Twig\Template->display(Array)
#6 /var/www/html/vendor/twig/twig/src/Template.php(394): __TwigTemplate_8ed8f0306d7b7d4508443c05bee61f62->doDisplay(Array, Array)
#7 /var/www/html/vendor/twig/twig/src/Template.php(367): Twig\Template->displayWithErrorHandling(Array, Array)
#8 /var/www/html/vendor/twig/twig/src/Template.php(379): Twig\Template->display(Array)
#9 /var/www/html/vendor/twig/twig/src/TemplateWrapper.php(38): Twig\Template->render(Array)
#10 /var/www/html/vendor/twig/twig/src/Environment.php(280): Twig\TemplateWrapper->render(Array)
#11 /var/www/html/vendor/craftcms/cms/src/web/View.php(482): Twig\Environment->render('_elements/table...', Array)
#12 /var/www/html/vendor/craftcms/cms/src/base/Element.php(1260): craft\web\View->renderTemplate('_elements/table...', Array)
#13 /var/www/html/vendor/craftcms/cms/src/controllers/ElementIndexesController.php(854): craft\base\Element::indexHtml(Object(verbb\comments\elements\db\CommentQuery), Array, Array, '*', 'index', true, true, false)
#14 /var/www/html/vendor/craftcms/cms/src/controllers/ElementIndexesController.php(177): craft\controllers\ElementIndexesController->elementResponseData(true, true)
#15 [internal function]: craft\controllers\ElementIndexesController->actionGetElements()
#16 /var/www/html/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array(Array, Array)
#17 /var/www/html/vendor/yiisoft/yii2/base/Controller.php(178): yii\base\InlineAction->runWithParams(Array)
#18 /var/www/html/vendor/yiisoft/yii2/base/Module.php(552): yii\base\Controller->runAction('get-elements', Array)
#19 /var/www/html/vendor/craftcms/cms/src/web/Application.php(349): yii\base\Module->runAction('element-indexes...', Array)
#20 /var/www/html/vendor/craftcms/cms/src/web/Application.php(650): craft\web\Application->runAction('element-indexes...', Array)
#21 /var/www/html/vendor/craftcms/cms/src/web/Application.php(311): craft\web\Application->_processActionRequest(Object(craft\web\Request))
#22 /var/www/html/vendor/yiisoft/yii2/base/Application.php(384): craft\web\Application->handleRequest(Object(craft\web\Request))
#23 /var/www/html/web/index.php(12): yii\base\Application->run()
#24 {main} {"memory":5828856,"exception":"[object] (TypeError(code: 0): verbb\\comments\\elements\\Comment::__toString(): Return value must be of type string, null returned at /var/www/html/vendor/verbb/comments/src/elements/Comment.php:303)"} 
```

### Steps to reproduce

1. Upgrade to Craft 5 with existing comments
2. Open `/admin/comments`

### Craft CMS version

5.1.7

### Plugin version

3.0.0

### Multi-site?

No

**Comment by engram-design** [comment]
Fixed for the next release. To get this early, run `composer require verbb/comments:"dev-craft-5 as 3.0.0"`.

**Comment by engram-design** [comment]
Updated in [3.0.1](https://github.com/verbb/comments/releases/tag/3.0.1).
